---
title: "bmi_final"
author: "Qianshu Wang"
date: "2017/12/9"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
library(DT)
library(xtable)
library(readr)
library(tidyverse)
library(haven)
library(readxl)
library(janitor)
library(pander)
library(Hmisc)
library(multcomp)
library(reshape2)
library(faraway)
library(leaps)
library(HH)
library(broom)
library(olsrr)
```


Clean Data
```{r}
GHP = read_excel("./GHProject_Dataset.xlsx") %>%
  filter(ICU_Flag != 1)

GHP = GHP %>%
  separate(AdmitDtm, into = c("weekday", "date", "year"), sep = ",") %>% 
  mutate(date = paste(date, " 2016"), date = as.Date(date, format = " %B %d %Y")) %>%
  mutate(Cindex = if_else(Cindex == 1 & Cindex ==2, 1, Cindex), 
         Cindex = if_else(Cindex == 3 & Cindex == 4, 2, Cindex), 
         Cindex = if_else(Cindex >= 5, 3, Cindex)) %>% # 0 = normal, 1 = mild, 2 = moderate, 3 = severe
  mutate(MEWS = if_else(MEWS == 1, 0, MEWS), 
         MEWS = if_else((MEWS == 2) + (MEWS == 3) == 1, 1, MEWS), 
         MEWS = if_else((MEWS == 4) + (MEWS == 5) == 1, 2, MEWS), 
         MEWS = if_else(MEWS > 5, 3, MEWS)) # 0 = normal, 1 = increase caution, 2 = further deterioration, 3 = immediate action required
GHP = GHP %>%
  group_by(PatientID) %>%
  filter(date == min(date)) %>%
  clean_names() %>%
  mutate(log_losdays2 = log(losdays2), log_o2sat = log(o2sat), log_resp = log(respirationrate), squre_resp = (respirationrate)^2,  log_bmi = log(bmi), squre_o2sat = (o2sat)^2, log_heart = log(heartrate))

#write.csv(GHP, "GHP.csv")
```

deal with missing values
```{r na value}
attach(GHP)
boxplot(bpsystolic)
boxplot(o2sat)
boxplot(temperature)
boxplot(heartrate)
boxplot(respirationrate)
boxplot(bpdiastolic)
boxplot(bmi)
boxplot(ageyear)
boxplot(cindex)

histogram(bpsystolic)
histogram(o2sat)
histogram(temperature)
histogram(heartrate)
histogram(respirationrate)
histogram(bpdiastolic)
histogram(bmi)
histogram(ageyear)
histogram(cindex)
histogram(log_bmi) #bmi should be log

```

replace na with median
```{r}
replace_na_w_median = function(vector){
  if (is.numeric(vector)) {
    vector[is.na(vector)] = median(vector, na.rm = TRUE)
  } else if (is.character(vector)) {
    vector[is.na(vector)] = "unknown"
  }
  return(vector)
}

GHP_missing_to_median = map_df(GHP, replace_na_w_median)
```


fit with mews

pair-wise scatterplot, also to check collinarity
```{r}
#pairs(~ log_losdays2  + bpsystolic + bpdiastolic + temperature + log_heart + log_o2sat + lbmi + log_resp + is30dayreadmit + cindex + evisit + ageyear, data = GHP)
```

anova tests for categorical data
```{r}
# attach(GHP)
# slr_gender = lm(log_losdays2 ~ gender)
# slr_maritalstatus = lm(log_losdays2 ~ maritalstatus)
# slr_insurancetype = lm(log_losdays2 ~ insurancetype)
# slr_religion = lm(log_losdays2 ~ religion)
# anova(slr_gender)
# anova(slr_maritalstatus)
# anova(slr_insurancetype)
# anova(slr_religion)
```


The full model is
```{r full model}
# fit all predictor:
mult.reg = lm(log_losdays2 ~ log_bmi +  o2sat + heartrate + bpsystolic + bpdiastolic + respirationrate + temperature + is30dayreadmit + cindex + evisit + ageyear + gender + race + religion + maritalstatus + insurancetype, data = GHP_missing_to_median)
  summary(mult.reg)
```

```{r}
stepwise <- step(mult.reg, direction = 'both')
summary(stepwise)
```

criterion-based variable selection 
```{r}
best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model), nvmax = 40, ...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  

best_subsets = best(mult.reg, nbest = 1)
pander(best_subsets)
```

the selected model
```{r}
best_mult = lm(log_losdays2 ~ mews + is30dayreadmit + cindex + evisit + ageyear + gender + insurancetype + religion + maritalstatus, data = GHP)
  summary(best_mult)
```

#check collinearity
```{r}
pander(vif(best_mult))
```

```{r}
best_mult = lm(log_losdays2 ~ log(bmi) + is30dayreadmit + cindex + evisit + ageyear + gender + insurancetype + bpdiastolic + bpsystolic + heartrate +respirationrate+temperature, data = GHP_missing_to_median)
  summary(best_mult)
  
par(mfrow = c(2, 2))
plot(best_mult)

stu_res<-rstandard(best_mult)
outliers_y<-stu_res[abs(stu_res)>2.5]
outliers_y

as.data.frame(influence.measures(best_mult_1))

inf = influence.measures(best_mult)
which(apply(inf$is.inf, 1, any))

ghp_remove <- GHP_missing_to_median[c(-6,-237,-285,-333,-378,-421,-526,-547,-620,-646,-726,-775,-794,-844,-858,-873,-884,-902,-1011,-1147,-1268,-1372,-1427,-1505,-1524,-1551,-1588,-1643,-1678,-1738,-1921,-1929,-2037,-2107,-2190,-2443,-2508,-2576,-2603,-2821,-2837,-2878,-2902,-2935,-2976,-3136,-3154,-3155,-3167,-3182,-3229,-3281,-3357,-3358,-3378,-3389,-3392,-3414,-3462),]

best_mult_1 = lm(log_losdays2 ~ log(bmi) + is30dayreadmit + cindex + evisit + ageyear + gender + insurancetype + bpdiastolic + bpsystolic + heartrate +respirationrate+temperature, data = ghp_remove)
  summary(best_mult_1)
  
inf_1 = influence.measures(best_mult_1)
which(apply(inf_1$is.inf, 1, any))
summary(inf)
  
ghp_outlier = GHP_missing_to_median[c(6,237,285,333,378,421,526,547,620,646,726,775,794,844,858,873,884,902,1011,1147,1268,1372,1427,1505,1524,1551,1588,1643,1678,1738,1921,1929,2037,2107,2190,2443,2508,2576,2603,2821,2837,2878,2902,2935,2976,3136,3154,3155,3167,3182,3229,3281,3357,3358,3378,3389,3392,3414,3462),]

best_mult_2 = lm(log_losdays2 ~ log(bmi) + is30dayreadmit + cindex + evisit + ageyear + gender + insurancetype + bpdiastolic + bpsystolic + heartrate +respirationrate+temperature, data = ghp_outlier)
  summary(best_mult_2)
```


